language: r
sudo: required
os: linux

jobs:
  include:
    - os: osx
      before_install:
        - |
          # Install older Mac SDK so that conda llvm (7) can be used
          # https://github.com/conda-forge/mpi-feedstock/issues/4
          export MACOSX_DEPLOYMENT_TARGET=${MACOSX_DEPLOYMENT_TARGET:-10.9}
          export SDKROOT="$(xcode-select -p)/Platforms/MacOSX.platform/Developer/SDKs/MacOSX${MACOSX_DEPLOYMENT_TARGET}.sdk"
          echo "MACOSX_DEPLOYMENT_TARGET = ${MACOSX_DEPLOYMENT_TARGET}"
          echo "SDKROOT = ${SDKROOT}"

          if [[ ! -d ${SDKROOT} || "$OSX_FORCE_SDK_DOWNLOAD" == "1" ]]; then
             echo "Downloading ${MACOSX_DEPLOYMENT_TARGET} sdk to ${SDKROOT}"
             curl -L -O https://github.com/phracker/MacOSX-SDKs/releases/download/10.13/MacOSX${MACOSX_DEPLOYMENT_TARGET}.sdk.tar.xz
             tar -xf MacOSX${MACOSX_DEPLOYMENT_TARGET}.sdk.tar.xz -C "$(dirname "$SDKROOT")"
             ls "$(dirname "$SDKROOT")"
             # set minimum sdk version to our target
             plutil -replace MinimumSDKVersion -string ${MACOSX_DEPLOYMENT_TARGET} $(xcode-select -p)/Platforms/MacOSX.platform/Info.plist
             plutil -replace DTSDKName -string macosx${MACOSX_DEPLOYMENT_TARGET}internal $(xcode-select -p)/Platforms/MacOSX.platform/Info.plist
             printf "SDKROOT:\n  - ${SDKROOT}  # [osx]\n" > ~/conda_build_config.yaml
          fi
      script:
        - echo "install.packages(\"Rcpp\", repos=\"http://cloud.r-project.org\")" | R --n
