name: Python Package using Conda

on:
  push:
    branches-ignore:
      - 'gh-pages'

env:
  NUMPY: numpy
  MATPLOTLIB: matplotlib
  MPLBACKEND: agg
  JSONSCHEMA: jsonschema
  INSTALLR: 1
  INSTALLC: 1
  INSTALLFORTRAN: 1
  INSTALLSBML: 1
  INSTALLLPY: 0
  INSTALLZMQ: 1
  INSTALLRMQ: 0
  INSTALLTRIMESH: 1
  INSTALLPYGMENTS: 1
  BUILDDOCS: 0

jobs:
  build_pip:
    name: Build (${{ matrix.python-version }}, ${{ matrix.os }}, ${{ matrix.install-method }})
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 5
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6]
        install-method: [pip]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Turn off C installation on Windows & patch TEMP
      if: matrix.os == 'windows-latest' && matrix.install-method == 'pip'
      shell: bash -l {0}
      run: |
        echo "INSTALLC=0" >> $GITHUB_ENV
        echo "TMPDIR=$USERPROFILE\AppData\Local\Temp" >> $GITHUB_ENV
        echo "TEMP=$USERPROFILE\AppData\Local\Temp" >> $GITHUB_ENV
    - name: Set up MSVC Compiler
      uses: ilammy/msvc-dev-cmd@v1
      if: matrix.os == 'windows-latest' && env.INSTALLC == 1
    - name: Set up Python
      uses: actions/setup-python@v2
      if: matrix.install-method == 'pip'
      with:
        python-version: ${{ matrix.python-version }}
    - name: Check Python version
      if: matrix.os == 'macos-latest'
      run: |
        which python
        python --version
    - name: Install dependencies
      run: python utils/ci_setup.py ${{ matrix.install-method }} deploy
    - name: Verify installation
      run: python utils/ci_setup.py ${{ matrix.install-method }} verify
    - name: Non-example tests
      run: yggtest --ci
    - name: Example tests
      run: yggtest --ci --with-examples
    - name: Upload coverage report
      uses: codecov/codecov-action@v1

  build_rmq:
    name: Build RMQ (${{ matrix.python-version }}, ${{ matrix.os }}, ${{ matrix.install-method }})
    runs-on: ${{ matrix.os }}
    env:
      INSTALLRMQ: 1
    strategy:
      max-parallel: 5
      matrix:
        os: [ubuntu-latest]
        python-version: [3.6]
        install-method: [pip]
      fail-fast: false
    services:
      rabbitmq:
        image: rabbitmq:latest
        # ports:
        #   - 5672/tcp
        options: --health-cmd "rabbitmqctl node_health_check" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python
      uses: actions/setup-python@v2
      if: matrix.install-method == 'pip'
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: python utils/ci_setup.py ${{ matrix.install-method }} deploy
    - name: Verify installation
      run: python utils/ci_setup.py ${{ matrix.install-method }} verify
    - name: Non-example tests
      run: yggtest --ci
    - name: Example tests
      run: yggtest --ci --with-examples
    - name: Upload coverage report
      uses: codecov/codecov-action@v1

  build_conda:
    name: Build (${{ matrix.python-version }}, ${{ matrix.os }}, ${{ matrix.install-method }})
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 5
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6]
        install-method: [conda]
        include:
          - os: ubuntu-latest
            python-version: 3.8
            install-method: conda
      fail-fast: false
    defaults:
      run:
        shell: bash -l {0}
    env:
      GHA_SHELL: bash

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Patch TEMP on Windows
      if: matrix.os == 'windows-latest'
      run: |
        echo "TMPDIR=$USERPROFILE\AppData\Local\Temp" >> $GITHUB_ENV
        echo "TEMP=$USERPROFILE\AppData\Local\Temp" >> $GITHUB_ENV
    - name: Set up MSVC Compiler
      uses: ilammy/msvc-dev-cmd@v1
      if: matrix.os == 'windows-latest' && env.INSTALLC == 1
    # - name: Set up miniconda in base env
    #   uses: conda-incubator/setup-miniconda@v2
    #   if: matrix.install-method == 'conda'
    #   with:
    #     auto-update-conda: true
    #     channels: conda-forge
    #     use-only-tar-bz2: true
    #     activate-environment: ''
    - name: Set up Python base environment
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Check Python version
      if: matrix.os == 'macos-latest'
      run: |
        which python
        python --version
    - name: Build package
      run: python utils/ci_setup.py ${{ matrix.install-method }} build
    - name: Set up miniconda test environment
      uses: conda-incubator/setup-miniconda@v2
      if: matrix.install-method == 'conda'
      with:
        # TODO: Move autoupdate into script?
        # auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        channels: conda-forge
        # channel-priority: strict
        use-only-tar-bz2: true
    - name: Add miniconda bin to path and initialize conda shell
      if: matrix.install-method == 'conda'
      run: |
        echo "PATH=$HOME/miniconda/bin:$PATH" >> $GITHUB_ENV
        # conda init ${{ env.GHA_SHELL }}
    # - name: Source bash_profile so that changes take effect
    #   if: matrix.install-method == 'conda' && matrix.os != 'ubuntu-latest'
    #   run: source ~/.bash_profile
    # - name: Source bashrc so that changes take effect
    #   if: matrix.install-method == 'conda' && matrix.os == 'ubuntu-latest'
    #   run: source ~/.bashrc
    - name: Install old MacOSX SDK for compatibility with the conda llvm (7)
      if: matrix.os == 'macos-latest' && matrix.install-method == 'conda'
      run: ./utils/setup_old_mac_sdk.sh
    - name: Install dependencies
      run: python utils/ci_setup.py ${{ matrix.install-method }} deploy --without-build
    - name: Start RabbitMQ Server
      if: env.INSTALLRMQ == 1 && matrix.os != 'windows-latest'
      run: ./utils/setup_rabbitmq.sh
    - name: Verify installation
      run: python utils/ci_setup.py ${{ matrix.install-method }} verify
    - name: Non-example tests
      run: yggtest --ci
    - name: Example tests
      run: yggtest --ci --with-examples
    - name: Upload coverage report
      uses: codecov/codecov-action@v1
  docs:
    name: Build the Docs
    runs-on: ubuntu-latest
    env:
      BUILDDOCS: 1
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: python utils/ci_setup.py pip deploy
    - name: Verify installation
      run: python utils/ci_setup.py pip verify
    - name: Build the docs
      run: |
        cd docs
        make autodoc
        cd ../
    - name: Publish docs to Github pages
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: docs/build/html/
  deploy:
    name: Publish package
    needs: [build_pip, build_conda, build_rmq, docs]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: python utils/ci_setup.py pip deploy
    - name: Verify installation
      run: python utils/ci_setup.py pip verify
    - name: Build the package
      run: |
        python setup.py sdist
        python setup.py bdist_wheel
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.pypi }}
        skip_existing: true
        
