name: Python Package using Conda

on:
  push:
    branches-ignore:
      - 'gh-pages'

env:
  NUMPY: numpy
  MATPLOTLIB: matplotlib
  MPLBACKEND: agg
  JSONSCHEMA: jsonschema
  INSTALLR: 1
  INSTALLC: 1
  INSTALLFORTRAN: 1
  INSTALLSBML: 1
  INSTALLLPY: 0
  INSTALLZMQ: 1
  INSTALLRMQ: 0
  INSTALLTRIMESH: 1
  INSTALLPYGMENTS: 1
  BUILDDOCS: 0

jobs:
  build_pip:
    name: Build (${{ matrix.python-version }}, ${{ matrix.os }}, ${{ matrix.install-method }}, ${{ matrix.test-flags }}), Install C = ${{ matrix.install-c }}
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 5
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6]
        install-method: [pip]
        test-flags: [--long-running, --test-suite=examples]
        install-c: [true]
        include:
          - os: windows-latest
            python-version: 3.6
            install-method: pip
            test-flags: --long-running
            install-c: false
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set C installation based on matrix value
      if: matrix.install-c != true
      shell: bash -l {0}
      run: echo "INSTALLC=0" >> $GITHUB_ENV
    - name: Patch TEMP/TMPDIR on Windows
      if: matrix.os == 'windows-latest' && matrix.install-method == 'pip'
      shell: bash -l {0}
      run: |
        echo "TMPDIR=$USERPROFILE\\AppData\\Local\\Temp" >> $GITHUB_ENV
        echo "TEMP=$USERPROFILE\\AppData\\Local\\Temp" >> $GITHUB_ENV
    - name: Set VCPKG_ROOT on Windows
      if: matrix.os == 'windows-latest' && matrix.install-method == 'pip' && env.INSTALLC == 1
      shell: bash -l {0}
      run: echo "VCPKG_ROOT=C:\\vcpkg" >> $GITHUB_ENV
    - name: Set up MSVC Compiler
      uses: ilammy/msvc-dev-cmd@v1
      if: matrix.os == 'windows-latest' && env.INSTALLC == 1
      with:
        toolset: 14.0
    - name: Cache pip - Linux
      uses: actions/cache@v2
      if: startsWith(runner.os, 'Linux')
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache pip - MacOS
      uses: actions/cache@v2
      if: startsWith(runner.os, 'macOS')
      with:
        path: ~/Library/Caches/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache pip - Windows
      uses: actions/cache@v2
      if: startsWith(runner.os, 'Windows')
      with:
        path: ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Set up Python
      uses: actions/setup-python@v2
      if: matrix.install-method == 'pip'
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: python utils/setup_test_env.py install ${{ matrix.install-method }}
    - name: Verify installation
      run: python utils/setup_test_env.py verify
    - name: Compile libraries
      run: yggcompile
    - name: Run tests
      run: yggtest --ci ${{ matrix.test-flags }}
    - name: Upload coverage report
      uses: codecov/codecov-action@v1
    # - name: Start SSH session
    #   uses: luchihoratiu/debug-via-ssh@main
    #   if: ${{ failure() }}
    #   with:
    #     NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    #     SSH_PASS: ${{ secrets.SSH_PASS }}

  build_rmq:
    name: Build RMQ (${{ matrix.python-version }}, ${{ matrix.os }}, ${{ matrix.install-method }})
    runs-on: ${{ matrix.os }}
    env:
      INSTALLRMQ: 1
      INSTALLAPY: 1
    strategy:
      max-parallel: 5
      matrix:
        os: [ubuntu-latest]
        python-version: [3.6]
        install-method: [pip,conda]
        test-flags: [--long-running]
      fail-fast: false
    services:
      rabbitmq:
        image: rabbitmq:latest
        ports:
          - 5672:5672
        options: --health-cmd "rabbitmqctl node_health_check" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python
      uses: actions/setup-python@v2
      if: matrix.install-method == 'pip'
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: python utils/setup_test_env.py install ${{ matrix.install-method }}
    - name: Verify installation
      run: python utils/setup_test_env.py verify
    - name: Compile libraries
      run: yggcompile
    - name: Run tests
      run: yggtest --ci ${{ matrix.test-flags }}
    - name: Upload coverage report
      uses: codecov/codecov-action@v1
    # - name: Start SSH session
    #   uses: luchihoratiu/debug-via-ssh@main
    #   if: ${{ failure() }}
    #   with:
    #     NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    #     SSH_PASS: ${{ secrets.SSH_PASS }}

  build_conda:
    name: Build (${{ matrix.python-version }}, ${{ matrix.os }}, ${{ matrix.install-method }})
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 5
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6]
        install-method: [conda]
        test-flags: [--long-running]  # , --test-suite=examples]
        include:
          - os: ubuntu-latest
            python-version: 3.8
            install-method: conda
      fail-fast: false
    defaults:
      run:
        shell: bash -l {0}
    env:
      GHA_SHELL: bash

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Patch TEMP on Windows
      if: matrix.os == 'windows-latest'
      run: |
        echo "TMPDIR=$USERPROFILE\AppData\Local\Temp" >> $GITHUB_ENV
        echo "TEMP=$USERPROFILE\AppData\Local\Temp" >> $GITHUB_ENV
    - name: Cache conda
      uses: actions/cache@v1
      env:
        # Increase this value to reset cache if file not changed
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
          hashFiles('recipe/meta.yaml') }}
    - name: Set up miniconda base environment on Windows
      uses: conda-incubator/setup-miniconda@v2
      if: matrix.install-method == 'conda' && matrix.os == 'windows-latest'
      with:
        channels: conda-forge
        use-only-tar-bz2: true
        activate-environment: ''
        # auto-activate-base: false
    - name: Set up MSVC Compiler
      uses: ilammy/msvc-dev-cmd@v1
      if: matrix.os == 'windows-latest' && env.INSTALLC == 1
    # - name: Record location of MSVC tools on Windows
    #   if: matrix.os == 'windows-latest' && env.INSTALLC == 1
    #   run: |
    #     echo "YGG_LINK_PATH=$(which link.exe)" >> $GITHUB_ENV
    #     echo "YGG_MSVC_BIN=$(dirname $(which link.exe))" >> $GITHUB_ENV
    # This step and the next allows conda to be called before the
    # conda-incubator/setup-miniconda@v2 action is used to create the test
    # environment so that the package can be built in the base environment.
    - name: Add miniconda bin to path - Unix
      if: matrix.install-method == 'conda' && matrix.os != 'windows-latest'
      run: |
        echo "PATH=$CONDA/bin:$PATH" >> $GITHUB_ENV
    - name: Change ownership of conda on MacOS
      shell: bash  # --noprofile --norc -eo pipefail {0}
      if: matrix.os == 'macos-latest'
      run: |
        sudo chown -R $(whoami) $CONDA
    - name: Build package
      shell: bash --noprofile --norc -eo pipefail {0}
      run: python utils/setup_test_env.py build ${{ matrix.install-method }} --python ${{ matrix.python-version }}
    - name: Set up miniconda test environment
      uses: conda-incubator/setup-miniconda@v2
      if: matrix.install-method == 'conda'
      with:
        # TODO: Move autoupdate into script?
        # auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        channels: conda-forge
        use-only-tar-bz2: true
        # channel-priority: strict
    - name: Install old MacOSX SDK for compatibility with the conda llvm (7)
      if: matrix.os == 'macos-latest' && matrix.install-method == 'conda'
      run: ./utils/setup_old_mac_sdk.sh
    - name: Install dependencies
      run: python utils/setup_test_env.py install ${{ matrix.install-method }} --without-build
    - name: Verify installation
      run: python utils/setup_test_env.py verify
    - name: Compile libraries
      run: yggcompile
    - name: Run tests
      run: yggtest --ci ${{ matrix.test-flags }}
    - name: Generate XML version of coverage report and check for coverage report
      run: |
        coverage xml
        ls -la
    - name: Upload coverage report
      uses: codecov/codecov-action@v1
    # - name: Start SSH session
    #   uses: luchihoratiu/debug-via-ssh@main
    #   if: ${{ failure() }}
    #   with:
    #     NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    #     SSH_PASS: ${{ secrets.SSH_PASS }}
  docs:
    name: Build the Docs
    runs-on: ubuntu-latest
    env:
      BUILDDOCS: 1
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: python utils/setup_test_env.py install pip
    - name: Verify installation
      run: python utils/setup_test_env.py verify
    - name: Build the docs
      run: |
        cd docs
        make autodoc
        cd ../
    - name: Publish docs to Github pages
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: docs/build/html/
  deploy:
    name: Publish package
    needs: [build_pip, build_conda, build_rmq, docs]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: python utils/setup_test_env.py install pip
    - name: Verify installation
      run: python utils/setup_test_env.py verify
    - name: Build the package
      run: |
        python setup.py sdist
        python setup.py bdist_wheel
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.pypi }}
        skip_existing: true
        
