name: Python Package using Conda

on: [push]

jobs:
  build:
    name: Build (${{ matrix.python-version }}, ${{ matrix.os }})
    env:
      INSTALLR: 1
      INSTALLC: 1
      INSTALLFORTRAN: 1
      INSTALLSBML: 1
      INSTALLZMQ: 1
      INSTALLRMQ: 0
      INSTALLTRIMESH: 1
      INSTALLPYGMENTS: 1
      INSTALLLPY: 0
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 5
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.8]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        channels: conda-forge
    - name: Install old MacOSX SDK for compatibility with the conda llvm (7)
      shell: bash -l {0}
      run: |
        ./utils/setup_old_mac_sdk.sh
      if: matrix.os == 'macos-latest'
    # - name: Set up Python
    #   uses: actions/setup-python@v2
    #   with:
    #     python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda info
        conda list
        python utils/ci_setup.py conda deploy
    - name: Verify installation
      shell: bash -l {0}
      run: |
        python utils/ci_setup.py conda verify
    - name: Non-example tests
      shell: bash -l {0}
      run: |
        # conda install pytest
        # $CONDA/bin/pytest
        yggtest --ci
    - name: Example tests
      shell: bash -l {0}
      run: |
        yggtest --ci --with-examples
    - name: Upload coverage report
      uses: codecov/codecov-action@v1
